#!/bin/sh

cd `dirname $0`

[[ $# > 0 ]] && target="$1" || target=1 

main=Main$target
src=$main.hs
so=$main.so

export PATH=$PATH:$HOME/.cabal/bin

[[ `stat $src -c %Y` > `stat $so -c %Y` ]] &&  boxghc $main.hs -o $main.so
exec boxlaunch.exe $main.so
