#!/bin/sh

cd `dirname $0`

[[ $# > 0 ]] && target="$1" || target=1 

if [[ "$1" -eq "rm" ]]; then
    rm *.{hi,o,so}
    exit
fi

main=Main$target
src=$main.hs
so=$main.so

export PATH=$PATH:$HOME/.cabal/bin

[[ `stat $src -c %Y 2>/dev/null` > `stat $so -c %Y` ]] &&  boxghc $main.hs -o $main.so

if [ -f "$main.so" ]; then
    exec boxlaunch.exe $main.so
fi
