#!/bin/sh

cd `dirname $0`

if [ "$1" = "-f" ] ; then
    force=1
    shift
fi

[[ $# > 0 ]] && target="$1" || target=1 

if [[ "$1" -eq "rm" ]]; then
    rm *.{hi,o,so}
    exit
fi

main=Main$target
src=$main.hs
so=$main.so

export PATH=$PATH:$HOME/.cabal/bin

if [ $so -ot $src ] || [ "$force" ] ; then
    boxghc $main.hs -o $main.so
fi

if [ -f "$main.so" ]; then
    exec boxlaunch.exe $main.so
fi
